
title: 'Curriculum Vitae - Guillermo Movia'
url: ''
# baseurl: '/online-cv' #change it according to your repository name
baseurl: '/'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Guillermo Movia
tagline: Web, comunicación y comunidades en la era del software y la cultura libres.
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: gmovia@protonamail.ch
website: unojoenelcielo.com.ar #do not add http://
github: deimidis
twitter: '@deimidis'

#Update all the sections by editing the files inside _includes folder.
